declare module '*.vue' {
  import Vue from 'vue'
  export default Vue
}

declare module '*.js'
declare module '@/components/Descriptions/index.js'
declare module '@/components/DescriptionsItem/index.js'

declare module 'vue-svgicon'
declare module 'qs'
declare module 'showdown'
declare module 'vue-grid-layout'
declare module 'echarts'
declare module 'clipboard'
declare module 'jquery'
declare module '@ztree/ztree_v3'
declare module 'vue-simple-uploader'
declare module 'sortablejs'
declare module 'bpmn-js/lib/Modeler'
declare module '@riophae/vue-treeselect'
// declare module 'element-ui'
declare module 'data' // 树组件数据源
// declare let ResizeObserver: any // dom尺寸调整观察
declare module '@riophae/vue-treeselect'
declare module 'file-saver'
declare module 'sockjs-client'
declare module 'stompjs'
declare module 'lodash.get'
declare module 'vuex-module-decorators'
declare module 'js-cookie'
declare module '@/styles/element-variables.scss'
declare module 'vue/dist/vue.esm'
declare module 'lodash.clonedeep'
declare module 'vue-cropper'
declare module 'lodash.debounce'
declare module 'lodash.throttle'
declare module 'lodash.isequal'
declare module 'lodash.chunk'
declare module 'lodash.difference'
declare module 'lodash.pullat'
declare module 'lodash.remove'
declare module 'lodash.sortby'
declare module 'bpmn-js/lib/NavigatedViewer'
declare module 'bpmn-js-properties-panel'
declare module 'bpmn-js-properties-panel/lib/provider/camunda'
declare module 'vue2-toast'
declare module 'ofd.js'
declare module '@/utils/sm4.js'
declare module '@/utils/hash.js'
declare module 'spark-md5'
declare module 'jsencrypt/bin/jsencrypt.min'
declare module '@/utils/uploader'
declare module '@/modules/demo/views/bpmnJs/bpmnData.bpmn'
declare module 'dagre-d3'
declare module 'd3'
declare module 'ic-map-ui'
declare module '@turf/turf'
declare module './assets/base64'
declare module '*.png' {
  const value: string
  export default value
}
declare module '@turf/intersect'
declare module '@types/ol`'
declare module 'pubsub-js'
declare module 'fox-preview-image'
